// Stub backend — generated by platform compiler

export type backendInterface = {
  _initializeAccessControlWithSecret: (token: string) => Promise<void>;
  [key: string]: unknown;
};

export type CreateActorOptions = {
  agentOptions?: Record<string, unknown>;
  actorOptions?: Record<string, unknown>;
};

export type OnProgress = (progress: number) => void;

export class ExternalBlob {
  id: string;
  url: string;
  onProgress?: OnProgress;

  constructor(id: string, url: string, onProgress?: OnProgress) {
    this.id = id;
    this.url = url;
    this.onProgress = onProgress;
  }

  static fromURL(url: string, onProgress?: OnProgress): ExternalBlob {
    return new ExternalBlob(url, url, onProgress);
  }

  async getBytes(): Promise<Uint8Array> {
    return new Uint8Array();
  }
}

export async function createActor(
  _canisterId: string,
  _uploadFile?: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile?: (bytes: Uint8Array) => Promise<ExternalBlob>,
  _options?: CreateActorOptions
): Promise<backendInterface> {
  return {
    _initializeAccessControlWithSecret: async (_token: string) => {},
  } as backendInterface;
}

export default {} as backendInterface;
